name: Delete Invitations

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'A comma-separated list of repos containing the invitations to delete (use the wildcard * for all)'
        required: true
        default: '*'
      only_expired:
        type: boolean
        description: 'Delete expired invitations only'
        required: true
        default: true

concurrency:
  group: outside_collaborators_delete_invitations
  cancel-in-progress: true

jobs:
  Check:
    name: "Delete"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml
      - name: Set Env Variables
        run: |
          echo "OUTSIDE_COLLABORATORS_GITHUB_ORG=${{ github.repository_owner }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_TOKEN=${{ secrets.OUTSIDE_COLLABORATORS_TOKEN }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_REPOS_DELETE_INVITATIONS=${{ inputs.repositories }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_ONLY_EXPIRED_INVITATIONS=${{ inputs.only_expired }}" >> ${GITHUB_ENV}
      - uses: actions/checkout@main
      - name: Run Handler
        run: |
          cd scripts
          ./delete-invitations.rb
      
